# roles/mariadb/vars/Debian.yml
---
#mariadb_apt_mirror: 'http://ftp.hosteurope.de'
#mariadb_apt_repositories:
#  - 'deb [arch=amd64,i386,ppc64el] {{ mariadb_apt_mirror }}/mirror/mariadb.org/repo/{{ mariadb_version }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main'
#  - 'deb-src {{ mariadb_apt_mirror }}/mirror/mariadb.org/repo/{{ mariadb_version }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main'

mariadb_apt_mirror: 'http://ftp.yz.yamagata-u.ac.jp'
mariadb_apt_repositories:
  - 'deb [arch=amd64,i386,ppc64el] {{ mariadb_apt_mirror }}/pub/dbms/mariadb/repo/{{ mariadb_version }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main'
  - 'deb-src {{ mariadb_apt_mirror }}/pub/dbms/mariadb/repo/{{ mariadb_version }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main'
  
mariadb_apt_keyserver: 'keyserver.ubuntu.com'
mariadb_apt_keyid: '0xF1656F24C74CD1D8'

mariadb_packages:
  - mariadb-server
  - mariadb-client
  - libmysqlclient-dev
  - python-pip

mariadb_pip_dependencies:
  - MySQL-python

mariadb_socket: /var/run/mysqld/mysqld.sock

mariadb_config_network: /etc/mysql/conf.d/network.cnf
mariadb_config_server: /etc/mysql/conf.d/server.cnf
mariadb_config_custom: /etc/mysql/conf.d/custom.cnf
