---
- src: geerlingguy.repo-remi
  when: ansible_os_family == 'RedHat'
- geerlingguy.ntp
- geerlingguy.nginx
- geerlingguy.php-versions
- geerlingguy.php
- geerlingguy.mysql
- src: geerlingguy.firewall
  when: ansible_os_family == 'Debian'
