- hosts: localhost
  connection: local
  vars_files:
    - vars/main.yml
    - vars/php.yml
    - vars/vhosts.yml

  vars:
    php_version: '7.2'
    php_webserver_daemon: nginx
    php_enable_php_fpm: true
    php_fpm_pool_user: nginx
    php_fpm_pool_group: nginx
#    nginx_conf_template: "{{ playbook_dir }}/templates/nginx.conf.j2"
#    nginx_vhost_template: "{{ playbook_dir }}/templates/vhost.j2"
    
    mysql_config_include_files:
      - name: 'server.cnf'
        src: '{{ playbook_dir }}/templates/server.cnf'
        force: true
    
    mysql_root_password: "root"
    mysql_databases:
      - name: "testDb"
        collation: utf8_general_ci
    mysql_users:
      - name: "testUser"
        password: "test"
        priv: "testDb.*:ALL"
    
  roles:
    - role: geerlingguy.repo-remi
      when: ansible_os_family == 'RedHat'
    - geerlingguy.ntp
    - geerlingguy.nginx
    - geerlingguy.php-versions
    - geerlingguy.php
    - geerlingguy.mysql

  tasks:
    # fix directory owner for Nginx
    - file: path=/var/log/nginx owner=root group=root mode=0700
    - file: path=/var/log/php-fpm owner=root group=root mode=0700
    - template: src={{ playbook_dir }}/templates/root_bash_profile.j2 dest=/root/.bash_profile owner=root group=root mode=0644
    - template: src={{ playbook_dir }}/templates/php_index.j2 dest=/usr/share/nginx/html/index.php
    - name: reload bash_profile
      shell: source /root/.bash_profile
