- hosts: localhost
  connection: local
  collections:
    - ansible.posix
    - community.general
    - community.mysql

  vars_files:
    - vars/main.yml
    - vars/www_{{ ansible_os_family }}.yml
    
  vars:
    ### PHP version ###
    php_version: '8.1'
    php_default_version_debian: "8.1"

    ### MariaDB version ###
    mariadb_version: '10.7'
    
    # sample database for Japanese testing
    mariadb_databases:
      - name: "testdb"
    mariadb_users:
      - name: "testuser"
        password: "test"
        priv: "testdb.*:ALL"
        host: "127.0.0.1"
    
  roles:
    - geerlingguy.repo-epel
    - role: geerlingguy.repo-remi
      when: (ansible_distribution == 'CentOS' and ansible_distribution_major_version == '8')
    - geerlingguy.ntp
    - nginxinc.nginx
    - geerlingguy.php-versions
    - geerlingguy.php
    - geerlingguy.php-mysql
    - mariadb

  pre_tasks:
    - selinux: state=disabled

  tasks:
    ##########################################################
    # Repository configuration
    ##########################################################
    - name: Install Remi repository
      dnf:
        name: 'https://rpms.remirepo.net/enterprise/remi-release-9.rpm'
        state: present
        disable_gpg_check: yes
      when: (ansible_distribution == 'CentOS' and ansible_distribution_major_version == '9')
    - name: Enable Remi repository
      shell:
        cmd: dnf config-manager --set-enabled remi
      when: (ansible_distribution == 'CentOS' and ansible_distribution_major_version == '9')

    ##########################################################
    # PHP configuration
    ##########################################################
    # fix log directory ownership
    - file: path=/var/log/php-fpm owner=root group=root mode=0700
      when: ansible_os_family == 'RedHat'

    # fix PHP directory ownership
    - file: path="/var/lib/php/opcache" owner=nginx group=nginx mode=0770
      when: ansible_os_family == 'RedHat'
    - file: path="/var/lib/php/session" owner=nginx group=nginx mode=0770
      when: ansible_os_family == 'RedHat'
    - file: path="/var/lib/php/wsdlcache" owner=nginx group=nginx mode=0770
      when: ansible_os_family == 'RedHat'

    ##########################################################
    # nginx configuration
    ##########################################################
    # fix directory ownership
    - file: path=/var/log/nginx owner=root group=root mode=0755
      when: ansible_os_family == 'RedHat'

    # fix Nginx log ownership
    - template: src="logrotate_nginx.j2" dest="/etc/logrotate.d/nginx" owner=root group=root mode=0644
      when: ansible_os_family == 'RedHat'
    - file: path="/var/log/nginx/access.log" owner=nginx group=nginx mode=0640
      when: ansible_os_family == 'RedHat'
    - file: path="/var/log/nginx/error.log" owner=nginx group=nginx mode=0640
      when: ansible_os_family == 'RedHat'
      
    # configure default SSL site
    - name: update Nginx default.conf
      template: src="default.conf.j2" dest="/etc/nginx/conf.d/default.conf" owner=root group=root mode=0644
      
    ##########################################################
    # firewall configuration
    ##########################################################
    - firewalld: service=http permanent=true state=enabled
    - firewalld: service=https permanent=true state=enabled
    - name: restart firewalld
      service: name=firewalld state=restarted enabled=yes

    ##########################################################
    # root tools
    ##########################################################
    # add root shell environment
    - template: src="root_bash_profile.j2" dest="/root/.bash_profile" owner=root group=root mode=0644
      when: ansible_os_family == 'RedHat'
    - template: src="root_bash_profile.j2" dest="/root/.profile" owner=root group=root mode=0644
      when: ansible_os_family == 'Debian'

    ##########################################################
    # PHP sample script
    ##########################################################
    # add php test scripts in default site
    - template: src="php_index.j2" dest="/var/www/html/index.php"
    - template: src="php_index2.j2" dest="/var/www/html/index2.php"