---
- src: geerlingguy.repo-remi
  when: ansible_os_family == 'RedHat'
- geerlingguy.ntp
- geerlingguy.nginx
- geerlingguy.php-versions
- geerlingguy.php
- geerlingguy.php-mysql
- src: geerlingguy.firewall
  when: ansible_os_family == 'Debian'
- src: bertvv.mariadb
  when: ansible_os_family == 'RedHat'
#- src: tschifftner.mariadb
#  when: ansible_os_family == 'Debian'
